"""post and asset tables

Revision ID: de15924d7c34
Revises: 6d2df1d82bce
Create Date: 2022-04-23 14:52:29.096249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de15924d7c34'
down_revision = '6d2df1d82bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=64), nullable=True),
    sa.Column('asset_desc', sa.String(length=200), nullable=True),
    sa.Column('asset_region', sa.String(length=64), nullable=True),
    sa.Column('asset_type', sa.String(length=64), nullable=True),
    sa.Column('super_theme', sa.String(length=64), nullable=True),
    sa.Column('micro_theme', sa.String(length=64), nullable=True),
    sa.Column('bloomberg_ticker', sa.String(length=64), nullable=True),
    sa.Column('sec_ref', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('asset_opinion', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_asset_name'), 'asset', ['asset_name'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_asset_asset_name'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
