"""new fielddatetime in asset model

Revision ID: f3fb80a6b26c
Revises: dbfd275a31bf
Create Date: 2022-04-23 18:14:39.505223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fb80a6b26c'
down_revision = 'dbfd275a31bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_asset_timestamp'), 'asset', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_timestamp'), table_name='asset')
    op.drop_column('asset', 'timestamp')
    # ### end Alembic commands ###
